services:
  # Backend Service
  - type: web
    name: uptime-monitor-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: cd .. && npm install && cd backend && npm install
    startCommand: node src/server.js
    healthCheckPath: /health
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://darexmucheri:cMd7EoTwGglJGXwR@cluster0.uwf6z.mongodb.net/uptime?retryWrites=true&w=majority&appName=Cluster0
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        sync: false

  # Frontend Service
  - type: web
    name: uptime-monitor-frontend
    env: static
    region: oregon
    plan: free
    rootDir: frontend
    buildCommand: cd .. && npm install && cd frontend && npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        sync: false

